#!/usr/bin/env python3
"""RULE-12 Runtime Validator: Detect and relocate misplaced one-time scripts.

Scans /scripts/ for files created during the current session that appear to be
one-time/session-specific scripts. Moves violations to /tmp/scripts/ automatically.

Usage:
    python3 scripts/validate_script_placement.py [--session-start <ISO-8601>] [--dry-run]

Exit codes:
    0: No violations found (or all resolved by auto-move)
    1: Unresolvable violation detected (pipeline should stop)
    2: Usage error
"""

import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
TMP_SCRIPTS_DIR = PROJECT_ROOT / "tmp" / "scripts"
STATE_FILE = PROJECT_ROOT / "tmp" / ".session-state.json"

# Known permanent scripts — never flag these
PERMANENT_SCRIPTS = {
    "check_deps.py",
    "create_placeholder.py",
    "experience.py",
    "generate_outputs.py",
    "recalc.py",
    "save_state.py",
    "smoke_test.py",
    "validate_urls.py",
    "validate_script_placement.py",
    "check_no_onetime_in_scripts.py",
    "chart_utils.py",
}

# Patterns that indicate a one-time/session-specific script
ONE_TIME_MARKERS = [
    r"session_id\s*=",
    r"tmp/.*\.json",
    r"/tmp/",
    r"hardcoded.*path",
    r"one[_-]?time",
    r"single[_-]?use",
    r"disposable",
    r"temporary\s+script",
    r"# Generated by .* at \d{4}-\d{2}-\d{2}",
    r"# Auto-generated for session",
]


def load_state():
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return None
    return None


def save_state(state):
    STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


def get_session_start(cli_arg=None):
    """Determine session start time from CLI arg or session state."""
    if cli_arg:
        return datetime.fromisoformat(cli_arg)
    state = load_state()
    if state and "started_at" in state:
        return datetime.fromisoformat(state["started_at"])
    # Fallback: 1 hour ago
    from datetime import timedelta
    return datetime.now() - timedelta(hours=1)


def is_session_created(filepath, session_start):
    """Check if file was created/modified during current session."""
    mtime = datetime.fromtimestamp(os.path.getmtime(filepath))
    return mtime >= session_start


def has_onetime_markers(filepath):
    """Check file content for one-time script markers."""
    try:
        content = filepath.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    for pattern in ONE_TIME_MARKERS:
        if re.search(pattern, content, re.IGNORECASE):
            return True
    return False


def validate_and_relocate(session_start, dry_run=False):
    """Scan /scripts/ and relocate one-time scripts to /tmp/scripts/."""
    if not SCRIPTS_DIR.exists():
        print("VALID: /scripts/ directory does not exist")
        return 0

    violations = []
    resolved = []

    for f in SCRIPTS_DIR.iterdir():
        if not f.is_file():
            continue
        if f.name in PERMANENT_SCRIPTS:
            continue
        if not f.suffix == ".py":
            continue

        # Check if created during this session AND has one-time markers
        session_file = is_session_created(f, session_start)
        has_markers = has_onetime_markers(f)

        if session_file and has_markers:
            violations.append(f)

    if not violations:
        print("VALID: No misplaced one-time scripts detected in /scripts/")
        return 0

    # Attempt to relocate violations
    for v in violations:
        if dry_run:
            print(f"DRY_RUN: Would move {v.name} → tmp/scripts/{v.name}")
            resolved.append(v)
            continue

        TMP_SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
        dest = TMP_SCRIPTS_DIR / v.name
        try:
            shutil.move(str(v), str(dest))
            resolved.append(v)
            print(f"MOVED: {v.name} → tmp/scripts/{v.name}")
        except OSError as e:
            print(f"ERROR: Cannot move {v.name}: {e}")

    # Log moves to session state
    if resolved and not dry_run:
        state = load_state()
        if state:
            if "script_relocations" not in state:
                state["script_relocations"] = []
            for r in resolved:
                state["script_relocations"].append({
                    "file": r.name,
                    "from": f"scripts/{r.name}",
                    "to": f"tmp/scripts/{r.name}",
                    "timestamp": datetime.now().isoformat(),
                    "reason": "RULE-12 violation: one-time script in /scripts/",
                })
            state["updated_at"] = datetime.now().isoformat()
            save_state(state)

    unresolved = set(violations) - set(resolved)
    if unresolved:
        print(f"UNRESOLVED: {len(unresolved)} violation(s) could not be relocated:")
        for u in unresolved:
            print(f"  - {u.name}")
        return 1

    print(f"RESOLVED: {len(resolved)} one-time script(s) relocated to /tmp/scripts/")
    return 0


def main():
    args = sys.argv[1:]
    session_start_arg = None
    dry_run = False

    i = 0
    while i < len(args):
        if args[i] == "--session-start" and i + 1 < len(args):
            session_start_arg = args[i + 1]
            i += 2
        elif args[i] == "--dry-run":
            dry_run = True
            i += 1
        elif args[i] in ("--help", "-h"):
            print(__doc__)
            sys.exit(0)
        else:
            print(f"Unknown argument: {args[i]}")
            sys.exit(2)

    session_start = get_session_start(session_start_arg)
    exit_code = validate_and_relocate(session_start, dry_run)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
